[[LLVMOpenMP]]
arch = "aarch64"
git-tree-sha1 = "807b3a94123d30a6923d6d303e22f466233a4ea6"
os = "macos"

    [[LLVMOpenMP.download]]
    sha256 = "1fdffb27e13954a1c3a1838047bfa3fba2728473216e1d9dcc9c095168451421"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.aarch64-apple-darwin.tar.gz"
[[LLVMOpenMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "495786256814a1e1ef0ec6e073bcfa75edfd748a"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "0bc39e56ce9a5519d6e8b62e2a96d4b6f59398381293905fa701b0e0eeab6104"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f0ff7e7e82d0677c59be682624b8eba5acf63a9"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "16d9144e78fc9fab3a1989c06a360ee8f48ecc08e11614a14408bae232d8c525"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "31b41ebefe0021e2d4aca896a327b3e5b8d8c170"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "c939ddeaadb7b168a9c714129819563ae14c826da559292400da875582c78e10"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.aarch64-linux-musl-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "420a5ed1edff59fdd1c65e9d33e126ab3dd86bfe"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "5e203f21ff747f5e090c93c9ea35ad3ec7bbeb8d60961551a683ac8b36aad718"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.aarch64-linux-musl-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "561c4c8095f7ef42ea126b89b00003a56a995042"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "4819d458213a607cfb1637b2bcf509f21e70ae5a9da17267d17211277f343f85"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "561c4c8095f7ef42ea126b89b00003a56a995042"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "4819d458213a607cfb1637b2bcf509f21e70ae5a9da17267d17211277f343f85"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e4e1f3fe8523032bedf08c7950867b4d9878d843"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "eeaa668e0644bc1e53df79accbbfd1957485d87a988f36c10548df2374b9af8e"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e4e1f3fe8523032bedf08c7950867b4d9878d843"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "eeaa668e0644bc1e53df79accbbfd1957485d87a988f36c10548df2374b9af8e"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b7a2a27447c745f526e7a893b6cb01a3e0522b78"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "b17b4487c55d8c3c7f68539e455bf3e40775bee3afe8e0a1bfc537a4544aaea8"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7a2a27447c745f526e7a893b6cb01a3e0522b78"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "b17b4487c55d8c3c7f68539e455bf3e40775bee3afe8e0a1bfc537a4544aaea8"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ecb42fef4f83ac8c257ed4b3958ef153a36a518"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "19e6a25c3981b3cfbb929b6d650d0a4bbc53ad7bb78afbe55d2a58a18ee1a5cd"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ecb42fef4f83ac8c257ed4b3958ef153a36a518"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "19e6a25c3981b3cfbb929b6d650d0a4bbc53ad7bb78afbe55d2a58a18ee1a5cd"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f254f8a3b0008bb44c64bb1c43db6da8f31bf7b4"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "c2d7e93faa4f10dbf991c74e68f2edde77f721bedc8ab48f90388c5d92bab945"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.i686-linux-gnu-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a67966577d61221e70a4cb715f62e682548a21c9"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "4aa82790d6195212ca06045fcd3f9997850e039508b1166a690085d09faf5d52"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.i686-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f1b36277583b89923774d14bda46ad3e0835ed3"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "f65d418519016f6d407ebf5815e4f39439113a0e6e712cc00f13f0ece655a1d8"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.i686-linux-musl-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "335b1be3e5e1b1a1c4ba55166dc7da707ad6e3a9"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "da0bc24e0ae234a4d76b253b8312e7438d40e3587eef16922259f5eeb04e3c76"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.i686-linux-musl-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe259f77f9e213a6119a8c43fb8d064a5f95a219"
os = "windows"

    [[LLVMOpenMP.download]]
    sha256 = "2f74d96615b3f9905120455595607b22ea889a4b2d9071751939efa5ec4833e3"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.i686-w64-mingw32-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56a7155dc2b9ba2b176659530acdce0e8f388452"
os = "windows"

    [[LLVMOpenMP.download]]
    sha256 = "65c83b0b9f487edf8d6cb3c5eedfd05c4920917c6ed4c4763e88899d45090f03"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.i686-w64-mingw32-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa2a67c6ac4b376e8600525060245516b6d49e5a"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "c17f89048fadd8cdc4f9b1e2679b395d1aca032ca5af21f8e8cce8e674d6bfdc"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e1c5369d065e23aa96927c005f4ebff8a9eb117"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "74af73a2af521b6581caeaf582fae823face6171b442267e4f35e63c3ad3b25f"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
git-tree-sha1 = "05631fe88103182e5b976176182dde49854f3833"
os = "macos"

    [[LLVMOpenMP.download]]
    sha256 = "a018c3a6074e23f2fbb0b5e124cc9fef1b5ecd626fbb424b8384ca92cfa5c7f2"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.x86_64-apple-darwin.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b871fd5fb944754e71b2510ebf68caf47c2191ff"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "8e3f1ebe7005b77a2540ec7365072b0c00fc320f81195f351e401643654d4daf"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3729aed4ee7852ae96ee4dcc05085792ba81ff47"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "953faabf28f62fea466a7e6d701d6d4867426090bf5b2c6e0cb4b8cd3cc10021"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4888607c427d703bce0d0b1d37a854ca20bfabb0"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "48c39f24c5bfcb1097660e1c33a13ee98959bb1ec000a3328ad65ad5cbc1b9a8"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.x86_64-linux-musl-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6d9f983aeb4c28e378a8490091b12401811fa7d"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "2a575b8a1904d2a63b2958e5ff4266b5f0f4faef00396039abe9ea29df475f8e"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.x86_64-linux-musl-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
git-tree-sha1 = "88e4b1dafb944c03c1a7c9bcd799be3340f271f0"
os = "freebsd"

    [[LLVMOpenMP.download]]
    sha256 = "dc6189c43f938d94bca64c505dce63eb8b8dde550fd498f8210cdfdf49cc98e0"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.x86_64-unknown-freebsd.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "12c8afd56007f1936223698f983379e07fbf048a"
os = "windows"

    [[LLVMOpenMP.download]]
    sha256 = "f6ffaf9e66b6ee3d695a1b0932b221fcb6b86202effacd2108afbe5f3c5cd8d2"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12c8afd56007f1936223698f983379e07fbf048a"
os = "windows"

    [[LLVMOpenMP.download]]
    sha256 = "f6ffaf9e66b6ee3d695a1b0932b221fcb6b86202effacd2108afbe5f3c5cd8d2"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v17.0.6+0/LLVMOpenMP.v17.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
