[[LLVMOpenMP]]
arch = "aarch64"
git-tree-sha1 = "66577feda65f2fcceacafdda531586e5875a6a45"
os = "macos"

    [[LLVMOpenMP.download]]
    sha256 = "fb9c79710ea5b259e7d799ae7fdad7873d32236592de5b5556d2a7640e5d2a65"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v19.1.7+0/LLVMOpenMP.v19.1.7.aarch64-apple-darwin.tar.gz"
[[LLVMOpenMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5173f15c521ed0dd97b3dc110bf9a9601dd13aa9"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "d070596a56c425eb199ec6f7c746f7d5b5768ce12f7df389c330098ac3b0ac02"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v19.1.7+0/LLVMOpenMP.v19.1.7.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e2b725147c24c952c8b52e482454c109e3da1f7"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "5584224e60b9ccb37c45c2407d3cd78b50592e52bcc35fd56c5299272d948022"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v19.1.7+0/LLVMOpenMP.v19.1.7.aarch64-linux-musl-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "aarch64"
git-tree-sha1 = "a916e2bc378583677e46e048009700ae8d1994ae"
os = "freebsd"

    [[LLVMOpenMP.download]]
    sha256 = "4c509aedc47a88eef7f7f709b5879def372b22b09bd40a477e47814b589e6cbc"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v19.1.7+0/LLVMOpenMP.v19.1.7.aarch64-unknown-freebsd.tar.gz"
[[LLVMOpenMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c62c3bb64fdf96007177907064ec6a5ac5fe264f"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "5415372a532763ef62ce9d9295e028bc73f0a514b7e573c514013f271b6ce990"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v19.1.7+0/LLVMOpenMP.v19.1.7.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a679d056f0e5a59a58e0283d936a3ecacfdcb4c2"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "98d2c99889a7c7de6c5634772b81fbf58ff4261d51953d51fa7b6695a8030eb5"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v19.1.7+0/LLVMOpenMP.v19.1.7.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b416252db68ab19b77cafbea68a90a94f93c221"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "4229da20021c63ff1748ae6639b2c6333c7916c25b05d81c379c675c235f356f"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v19.1.7+0/LLVMOpenMP.v19.1.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88fc8b0301df5c595743bc8280af4febaaf42935"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "de684e8dc6fb28b978a6650b240dbb02729b5e2f302033fe21045725bdd8c3fe"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v19.1.7+0/LLVMOpenMP.v19.1.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "026e452deb5f091277343f82a293c6d0169c9853"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "28ec973c1fbb10764cf6f63861204b771d6463159675585cb2b41c09c4582499"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v19.1.7+0/LLVMOpenMP.v19.1.7.i686-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57b818d4ce9a59cbc7040c50581d4748563ed0a8"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "49a4a3b872fa32bf2cbfd3c438176abb69cc3d41a8d4289f812e175dfab963c1"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v19.1.7+0/LLVMOpenMP.v19.1.7.i686-linux-musl-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f93478108f68c39534529f65727c2d95085d328"
os = "windows"

    [[LLVMOpenMP.download]]
    sha256 = "b4f39caf8010da6f3199fe8e4c26fde5344e07728ff7dd9ba9ebd35efe41ef3c"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v19.1.7+0/LLVMOpenMP.v19.1.7.i686-w64-mingw32-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c4379da43b0b6a85feb9b27d7fc83fb64b9ab34"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "cd8d1efa17d04bd8b3089fa98ee2088dde0658b5a6a65e980a63a6b53ee8e0fd"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v19.1.7+0/LLVMOpenMP.v19.1.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94d81dc5d9054ac2bdfa917f98ce93045c077a81"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "3258160c0b3c621abfcec241a34bd729afd4c800e7b37b7e21d19602c1d561c9"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v19.1.7+0/LLVMOpenMP.v19.1.7.riscv64-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
git-tree-sha1 = "b63fad9d98d0590fed67ad86ff896a89e91e3d4a"
os = "macos"

    [[LLVMOpenMP.download]]
    sha256 = "7f6a046a004e1a200a645ffc231d198821ab9f90a92a0d99f87aa56e08c870cc"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v19.1.7+0/LLVMOpenMP.v19.1.7.x86_64-apple-darwin.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68782c4c40b1a762c3150b76cea3824877d42ae7"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "24d5cd4389fba1bbe7902c9ad0d6319142f023952bb6cc916934fe633e922d65"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v19.1.7+0/LLVMOpenMP.v19.1.7.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61cbb4272c6f3b925f08bc54f29d36f882f29f90"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "7b4acec1160544e3f19c74f3f936639f9fb2e006b28a379167646ee79e306ce7"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v19.1.7+0/LLVMOpenMP.v19.1.7.x86_64-linux-musl-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
git-tree-sha1 = "6509c90da4c11f97e56ec07c7e89a6f8449b64fa"
os = "freebsd"

    [[LLVMOpenMP.download]]
    sha256 = "3cd18c077dadf28eb3c63d437299b185f86deb6a541739f807109f77f34fe825"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v19.1.7+0/LLVMOpenMP.v19.1.7.x86_64-unknown-freebsd.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6f0e7e7caf14733f945fca332ad20c097dac93b"
os = "windows"

    [[LLVMOpenMP.download]]
    sha256 = "e70afe87ae907cb04af157c595c048db536d104e1528e4405104b778976801f1"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v19.1.7+0/LLVMOpenMP.v19.1.7.x86_64-w64-mingw32-cxx11.tar.gz"
