[[LLVMOpenMP]]
arch = "aarch64"
git-tree-sha1 = "347b036ceb5931ff19901bc14e81b00cc915e3e7"
os = "macos"

    [[LLVMOpenMP.download]]
    sha256 = "427f8873fc72c6bd36ba7747b541c1ba21a362092b3c7ad306a714c0739bec7e"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v22.1.7+0/LLVMOpenMP.v22.1.7.aarch64-apple-darwin.tar.gz"
[[LLVMOpenMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "735a7e8c6882db21f7a5dbfe2536ae34eece1cde"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "5a10f9bb63c093a8ca254b3b3d7a2014e41a8208dc8ad4e24a6e25e40e4fa28b"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v22.1.7+0/LLVMOpenMP.v22.1.7.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c111fd3801bfebafe09b608886132031e6b1bbf"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "fe57cadc0b6062fe896e16e996effe53cfa869d9fa439879f4ce5a4ff234eb88"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v22.1.7+0/LLVMOpenMP.v22.1.7.aarch64-linux-musl-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "aarch64"
git-tree-sha1 = "bb62a9c9eab4e51313ba56d215bbdd9e25eabdc6"
os = "freebsd"

    [[LLVMOpenMP.download]]
    sha256 = "75cbf517342933d754dd77543302ee74c1d3e17e2631a57f833b54d3cf76d794"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v22.1.7+0/LLVMOpenMP.v22.1.7.aarch64-unknown-freebsd.tar.gz"
[[LLVMOpenMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2bc91c5f3bad61b1bde13ecdac283d4bc1456dd6"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "9ad7bd1581e9962c43ddcebcece11c4064b10949276ebc7ac26c685b3ed87ca8"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v22.1.7+0/LLVMOpenMP.v22.1.7.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfab6bca0f664248092246194118cafa6357e80f"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "df615a43a5798e6ba00fb46455397e2c50ea5b11c9680700c76a376e98b02755"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v22.1.7+0/LLVMOpenMP.v22.1.7.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33f67bee4f20fff1bf310174be43905594168081"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "09d8025770d21dd590bad4053680733e2409d26d67b96477cb45ec55e4755e1d"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v22.1.7+0/LLVMOpenMP.v22.1.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8fa96272f082829b11ee92ae7578170ba2905f49"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "0f19a6663bd379d84cb45f0ed8b86a7c7fb48a7e257f50680a9fb7bcc2781709"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v22.1.7+0/LLVMOpenMP.v22.1.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b170e88a96b4a6379391ff5b44fa4d3506f71d9"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "cb2fe39b86ddbda2f5fdbfa3ac5cc16b04b69370659222bb1e9e4687b1dfda36"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v22.1.7+0/LLVMOpenMP.v22.1.7.i686-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6e9e0cc6b3c60a6f8189abf902af3840f2e3547"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "a79aa2151900592ed0f8d1dab9cea066e7534ca12ab3105f7c2e29409ec0d4f0"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v22.1.7+0/LLVMOpenMP.v22.1.7.i686-linux-musl-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "471c4bc28153375b4914039c814fdf2162be64c4"
os = "windows"

    [[LLVMOpenMP.download]]
    sha256 = "22f1330fb5962fc73968e98f885fcfd5d9f8a5ae2cee667909e78f2830288d53"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v22.1.7+0/LLVMOpenMP.v22.1.7.i686-w64-mingw32-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cbc44abde852eb6341211eb43958cd4d039850b4"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "f8fb1a76bc8a2233b42bdc4325afb21de97a9336d7a91fda0c99aa2f82964fda"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v22.1.7+0/LLVMOpenMP.v22.1.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7291efc98bcf6f3cc3def6fc60091f563f7a2678"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "172585ff29614da5e37d5e03449bf1ff3912ce80fbb21d00238b8cec00ca5dc0"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v22.1.7+0/LLVMOpenMP.v22.1.7.riscv64-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
git-tree-sha1 = "a1a387c406290b29c2322c5f23a490971fa4b0dc"
os = "macos"

    [[LLVMOpenMP.download]]
    sha256 = "9b8b05eb72a9cda45f078a6697e0535936ba01f86ab2ad953fada351ec762f32"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v22.1.7+0/LLVMOpenMP.v22.1.7.x86_64-apple-darwin.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c1d82fa2b4a04b946eb4aa9a6760596239f4b8d"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "31c747135d06c0eef3e3ac00fa1e84f1f6251c50eb1a630e88e0e9bcbb69a6e6"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v22.1.7+0/LLVMOpenMP.v22.1.7.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "411a895c7f02a1c900d98646fc84bc4a5fe50284"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "23cdd9f7c3ced09c04d67de823483062131768312b760ad96bffb050557f4250"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v22.1.7+0/LLVMOpenMP.v22.1.7.x86_64-linux-musl-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
git-tree-sha1 = "6bcc8e51cf7a32698b15f736b48f879e22f0e679"
os = "freebsd"

    [[LLVMOpenMP.download]]
    sha256 = "d6184b7ae4fab4c2d2a0fbc504a99063ae8208f8560831ee45e96de096709fa1"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v22.1.7+0/LLVMOpenMP.v22.1.7.x86_64-unknown-freebsd.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f5e35a1724274f96dbc51f00680012117358be3"
os = "windows"

    [[LLVMOpenMP.download]]
    sha256 = "282be80f467273c50175f3d59e307c08f37b525a410c8d58bc1b7ac91ddd312c"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v22.1.7+0/LLVMOpenMP.v22.1.7.x86_64-w64-mingw32-cxx11.tar.gz"
