[[LLVMOpenMP]]
arch = "aarch64"
git-tree-sha1 = "57c35f685ff849c80197f224bf4bb67d25c2f44c"
os = "macos"

    [[LLVMOpenMP.download]]
    sha256 = "998ad0563ff5be062862f169deeedafb13bdae472ba21754d89fbacc7d5d6e37"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.aarch64-apple-darwin.tar.gz"
[[LLVMOpenMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9095b9b13b7bd3cecf25956259fcc1cd2704eec4"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "aa91c9a9471055faeab02a7c669e9e59c5bd0529534d3c1cfe340d413dd4aab2"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af17ba5243ea2ce5faadf3240e6b5d4b2482c798"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "e15de6269d3308d456307438f77c8f4c966682d37e9402fa47b80c2dfdc235c6"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "436815c8e6d037ec0224a7b021272fac1f139321"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "ac3ec86b4df78fff3c791b1b746c69d30a83349c4608f5c3b8bbe641e7fd03b0"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.aarch64-linux-musl-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1638a24ca928e9bfcb0aaf7590548dc376f5202d"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "d84831994253f6e93eb61e5c88ad214263a2b52136865f2ecdaf010865e8e1a9"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.aarch64-linux-musl-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9b0cb3e021b5655e191800e682eb200eeca33bc1"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "54403a21eba4a0fffb307fc732813b2aed1555a47ea55a2db218604e95b145aa"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cd168342130a3067fc9af358fb270b3f1becdad"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "d099209de367c61350cdc3a03313e3a5311731e330b471354204f8d9b3a2cc43"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2451d09d2816925a8872ee466bda975f749ebb9f"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "8562514249d260b18bb8399350c591163c505fc0e41bad601229305b6486c1a6"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "069dbf070210e4e1bf7db7d37300afeaf6b27383"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "d6220ee7edcd5fc14ed14d1e96d0e307ac2bb28b45bc4249b70b11bb16c56225"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b9034c0e907ea1aed22eb2e31783bdd3456d66b7"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "9d9e9c21a088af4bec7b6fcdfa7356aec6fbde06734afaea8487615d2956887a"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18b4ae2ea328ecd02d72d6761cdc51647109f743"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "a215d2587deeda4b320232d3c74acf195ce2d8b97a2f5c0e4de1fc6d1e9f40cc"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1b8205dc9be1c2552bae039ae89b478e93dede15"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "622e812a317e158ef4de4241d3dd832843e325068eb2225b614c21b0e08be516"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af300123ee1e1fe2df091cc0748fd3836542566f"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "4d9fdd4d3f6062ddb73e48510f2f7ecda395ffec0c8ab06a2416871f6f94e08d"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "25578c19787eef2660e6e68791714a1fc7b43c13"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "ba6ea08511b1fba88af2026cb1d18b78fe630800c19cb69e33a64e582ee83e99"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.i686-linux-gnu-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83d2bb55787be971fa879c91d3b90dc5f80e812b"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "985b2ee91e36460be1ebc7868a591d492b9ca2e048e4af6514904b20caf70333"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.i686-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a48cbe6666b45bbd5230866372cb9511ed2eab86"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "e53aeaa4c4843a5101aca6aeebfaaa07efd3758ddd9337c10a85a781caf9ab4e"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.i686-linux-musl-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97bda3777e12b9d486059d9943327b3654a880d4"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "9a7266ea67625d195dd3ca4a39b08ba0fcafaa45d8943dd7f309dfcb1e2aa376"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.i686-linux-musl-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94990ca45a73d59508b4af37f67996bb9709e3cc"
os = "windows"

    [[LLVMOpenMP.download]]
    sha256 = "60e8828afe3f576c6bacad7b3ed622d7bcac222036de01aa840a6ec7fb6d984b"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.i686-w64-mingw32-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eee3f90ddf5188cae65b8a9ae9b088859cc444b6"
os = "windows"

    [[LLVMOpenMP.download]]
    sha256 = "1d383fd9121545e6c704ef2be5ad99df33fa761a06e9691bb974d3e9fb0053da"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.i686-w64-mingw32-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "121582b53ab1670375756abe497e231953df9f3e"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "09c3e09db8a5a4ce81165da808347c8a8dc4930620fea0a501729e8800715595"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d41035516139436ca56e14cf372e996faf70f0b"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "69f4e82c8948857215e46ad17873f7920fb1cc1c88fcc2cfb86e1cc810eb43c7"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
git-tree-sha1 = "1c2467717366e5ddb17edb9758afd69a6eef3a69"
os = "macos"

    [[LLVMOpenMP.download]]
    sha256 = "6002f17752acb6516870c2b36595cf54ff0e31cabfd2d15954beaca3926dbbc1"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.x86_64-apple-darwin.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "75e4ac96305f12ef5f8c70f0a1491b5c7ff40b39"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "5873dae8ee4d83d39fa6773b55705591822157f4f9b6204e7f9cb24caefc7c67"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e147c6c1fe9fbfd7915e35a0df2f16d3e1e690a"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "1c344323c423783c69af84c1254f36d09cf42bb583f3b302ba20e001db5a7b58"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ddbaef41adc385a015166269e584bb418fce4f9"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "5ebe7e1f5b836e24610d5060cf2a7f8d0da560f27319316e49d999564eeddbc1"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.x86_64-linux-musl-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9318695ee04a333af6aedd857bb93ca5e4d0b0aa"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "96b0ae3eade78aaab3b481cb00d77b3fb4be9760c9d45f8d39e9cfef8bcd5552"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.x86_64-linux-musl-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
git-tree-sha1 = "e9d82d5cdc933b060a1e8d819ef1b2336ee1c31b"
os = "freebsd"

    [[LLVMOpenMP.download]]
    sha256 = "db1096baf6f517d71d65ca7a333f98ef7d4a26a4a1335eb2422f0b8f413e05a3"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.x86_64-unknown-freebsd.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9abeb09442d3d06d67cbd9830f68339362668e77"
os = "windows"

    [[LLVMOpenMP.download]]
    sha256 = "8d2a16a6d2582351adf7921a2f878c2609f792180d6b9bdeb1857ea4ffdbbc7d"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c30012d3db8b814a03f0a2ed0ae628425e9d3fc1"
os = "windows"

    [[LLVMOpenMP.download]]
    sha256 = "f26c94c1d8463cc91343c30f6b60a86a59bdf5e76f66ac519a076a6ba7259cf7"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v14.0.4+0/LLVMOpenMP.v14.0.4.x86_64-w64-mingw32-cxx11.tar.gz"
