[[LLVMOpenMP]]
arch = "aarch64"
git-tree-sha1 = "ae812358b4a3d6cd2ad2ec5bd9bf33200110960c"
os = "macos"

    [[LLVMOpenMP.download]]
    sha256 = "62ee82e1056b023423f0a946b4296819a67660d591b3ce99a9cc6627fbb4d9b1"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.aarch64-apple-darwin.tar.gz"
[[LLVMOpenMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f74d0f1db3bd0c3d3db18835575f8a1fa0df542"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "ac486222ad06f8d27ea287b40cbf75420a5e5a1e64ff6f685a13641676b31d6e"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7584592d2ff978fb6e354fbeb4e0f458732f96c5"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "433ddf78dd94241b40a2ef6764c1890d77b309fe9735f9d526f96a6eec43ffbc"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b0844fdcda0b3170017d4a8157600505625b7ef"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "ab789560d575dc76f65c158884a1d0edabb21f8a51504a82e74ae5e2d51cdb03"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b1cf04569580ec84a439aec828583fd404beb10"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "0de9edc34336f17c584e9a731858ba6dcd682edb954efb2b741ae11af140be74"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c14c30d144aebf12d3896c2aec0f84c049d1245"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "1fba0ae6c833813be9f5047c697cd69540a10f1c99f1f349190491a88eaf4bd6"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d341d0f2db4b85b50514f4f50b2c9ed0caf8c58"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "c4558e7deb74107ac1ccc255346782c84ea58600bdac4d7c73c1c2b2d1911844"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69a8ace58f82a1904a3f735ffd31357ee80acfe4"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "a893107aa2ea92137d679150104a909373fb287d453b2eafa8f7f0632782554f"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb2189e2ea744c20534ea0ecc2ebe62c6fe8ea83"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "3484bb33bb3de6e200a1315d5e47e53929d7817e6170a2745673bb360c30c3dd"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18fa94a69b2fe9e9355b59b87f31bca08b666953"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "0273f78cc3029f68c3783df5b29eb3ade3ba60f25459a07befae4f63cbf9f855"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "207bc62df362efbe6dedcd6911faef88471221eb"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "f8594e38d5e5b19c1c5514e1917b98e396ebe27f5a27597fd286d9cabcc8e69e"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e280713cdd4f22dbafd7ca1ce15fad5651209ed5"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "16f4cfb9f8a9d57f5e58484ec0f90ed8c831dcfabc5cb2539f7e21602376e5e5"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ec78e6fd55e38b6529a5514761ff66591bc540f"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "978ca8a97b7d55b5d8cda12390c487d6eded1956d05ead89f5441bedc21dd074"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc1486441bcd1d0ed920ea590ec4e713fb009620"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "3e2b54f3924cdfe6248fb988f4c386a69318d3e2c0121b0095a136830c9553eb"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14ae078cea0ea328805de6495b4297e8395ee272"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "b3569fd381762816432bc1d15768aa19ca9f899ee14d785903ab6cd80b7d598f"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d8c069c66b07298ff815a102b7079e0cd8c16c6c"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "f92730fe58c3c4242396b8945d5fa574a07f8a52679f251f3b6fc287c43b86f2"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08a6c453c114eda97323232518663ed39be2451f"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "aef03e5ca3dcf8207e634b2f81b763ab69fdf0e4af4addb8b1242717fec349ad"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f1f8adcf3732ba28977d18f1d75f243b5e290cc9"
os = "windows"

    [[LLVMOpenMP.download]]
    sha256 = "3accfb7b4206408fe239033b970b9e958c8350abee8de5a25d15053e32c91aec"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4bf41741f7d1a866158d5012e3623d244ca4c10e"
os = "windows"

    [[LLVMOpenMP.download]]
    sha256 = "cfd00cf84028acf237079cf20f3f75e2c64ed094368659320dda6b2c585cfe35"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a464b5e569e81a6ba8d8fb452685fa85602e8526"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "4f796a9e103b2d3f60bfbfbe2a8a24c76cc594d9a9efdca053dad8da078eda13"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8176fc4ada025c700dcfa8bb16dd14fc8acefb42"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "ed8558f6343d1e5eef79769b72e82e795b1e864b4639288e2958b3aff3f3d28b"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
git-tree-sha1 = "ff978bd6bbd3b910044de56e023843abc7fbc961"
os = "macos"

    [[LLVMOpenMP.download]]
    sha256 = "95571f3b5b7ddfd805e9501c9f02f07e34e05fd8a4ac9a748742addb8a4c8ddb"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.x86_64-apple-darwin.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ba317c508fe97a5244a32a7dc3748958b2ea0fee"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "142a5841e71ee0caef7f71703adff793dcffcf3bbc47ab4666532a3422576f96"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ca4885a742c7177ea6fd5fdc5d2b586d7cec703"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "bd706f0fae19032edf8bcb5c86b4c10deb1a01ac3dd3f8ce594654cb09b02c1d"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "14bd58c84f9a0ae9ac3e72eeeb320b1a51074bc5"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "160862f796fe1538953ac7e6c55df34211e02b1a0acfa4fd8e81de4cdaf2d3bf"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4dd8dd9019bc1bc1343154d6e6c0e8bb8cf612c5"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "5aa91735d26336632e3a067f33fa05d73e11741ce4f7cdfd160a6359d9a6f045"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
git-tree-sha1 = "d1b52e597c7f403802c881f43cfae921c4a28cf6"
os = "freebsd"

    [[LLVMOpenMP.download]]
    sha256 = "78c28068b56802d11a59d2aaaab89b17a38631e6650bea153399f91866a0a312"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b42355a1a63c11749fad3ca8b22b8262c65da1e5"
os = "windows"

    [[LLVMOpenMP.download]]
    sha256 = "f85fb3d08f2eea2813503bb6f1e65522433ffb54b16d2029a9897526aa026008"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b81a6912e856ff7f1364dc3c380ad8cbfb02bbe2"
os = "windows"

    [[LLVMOpenMP.download]]
    sha256 = "b7addfad73b824ddb943d44663d742aaed1bc23fb8a714a0039165c1f8d83887"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v13.0.1+0/LLVMOpenMP.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
