[[LLVMOpenMP]]
arch = "aarch64"
git-tree-sha1 = "53ddf87decc5c59dd0133bb138c1cadf0533349c"
os = "macos"

    [[LLVMOpenMP.download]]
    sha256 = "9722aa0e65ae26d46aac38b526b95c04b58c9f875dada3453d9fabc7bfc9c6e8"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v20.1.8+0/LLVMOpenMP.v20.1.8.aarch64-apple-darwin.tar.gz"
[[LLVMOpenMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cb5e5d85020561525cc905b141ebe279132a295"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "0ab24b9f8ae5f85f56645e37a52982c26df55b9dfd6b2f25033fb75be1af78e0"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v20.1.8+0/LLVMOpenMP.v20.1.8.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5e05d23f7ce70514a26167f0cfe16ad232dec90"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "89405b66882c4d0f29374a8181e1f09b19d3331b07b05e66e31c612753fd93b1"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v20.1.8+0/LLVMOpenMP.v20.1.8.aarch64-linux-musl-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "aarch64"
git-tree-sha1 = "9b93c9a3cf456ba4a5888f16a029223e82b00a4a"
os = "freebsd"

    [[LLVMOpenMP.download]]
    sha256 = "f79cfd925bb0a5824075c1cc75fce0a26783ff30084f9921ba0fb56694ef0e2f"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v20.1.8+0/LLVMOpenMP.v20.1.8.aarch64-unknown-freebsd.tar.gz"
[[LLVMOpenMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b3fe6a040075d70dd8d1c9cd72dbbc9c6acc1fb"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "1a748065cc0163a6c8e706971540f8ae15c3cd5ba4a42efde2ca7901ebe258b2"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v20.1.8+0/LLVMOpenMP.v20.1.8.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8840db370c08f178f09599538484e2153a6ece53"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "f0530c208a7183081484e640a60e7613368eda11500d6d5d156f4d71c08d847a"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v20.1.8+0/LLVMOpenMP.v20.1.8.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6dc22112d1c71224169c2bbc2dc1b96e789f7cf2"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "c9e5f254b20e3deffaa02f4598b4cfa951b341ca3c25d0885293e68847a270f8"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v20.1.8+0/LLVMOpenMP.v20.1.8.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4be07e51d28bfd15a0e85b151fd911abc0e798b1"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "765c6e91749192131ad705b1303afb98d0777d36b77bf97addb1e1ff4afbf249"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v20.1.8+0/LLVMOpenMP.v20.1.8.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4985d760db3edb72f5e81cd8e5be840f3394571b"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "a4cc638564a2221de0721962fd5e31abdc8c1ed4059862924058c22576762fc1"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v20.1.8+0/LLVMOpenMP.v20.1.8.i686-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e715d728df134641797f8f397dcd89dfdb734b6"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "b1fef5a9a6f6cb7d80f2a78f9aff95e491b1495dd54e06c97615fa2d384b92ee"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v20.1.8+0/LLVMOpenMP.v20.1.8.i686-linux-musl-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32e96398c7c9bcc37d56fd9ba1063138fcf3c7ed"
os = "windows"

    [[LLVMOpenMP.download]]
    sha256 = "8d77f49a2f7f5000113788e70c90608a8f0e8891ef9e6bbd47fc8cf101466607"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v20.1.8+0/LLVMOpenMP.v20.1.8.i686-w64-mingw32-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb12560272e40138a6774d23e92e302c34d77846"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "1a62b6271ff3604af00d5bd63e0714fe8dc89ad73b99c7eba017b292f9ee2f9f"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v20.1.8+0/LLVMOpenMP.v20.1.8.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0fd79d72f9d65d440490a19d095ad602849ba0c"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "8a8df39d00ee88409549c329b67f0b157b08dcb3dee56fc28a13bebc99a996b7"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v20.1.8+0/LLVMOpenMP.v20.1.8.riscv64-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
git-tree-sha1 = "ff85b232dd02c351fccffa3f6d16edc50bda1f3d"
os = "macos"

    [[LLVMOpenMP.download]]
    sha256 = "657b3f98bc4260623290e49dba2737cd3a03ffa4e324ce0ba320220e1a170526"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v20.1.8+0/LLVMOpenMP.v20.1.8.x86_64-apple-darwin.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a3c24b35d1663bf7ca80b506550f65661439584a"
libc = "glibc"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "8dc4dd66b9b24fb9c7527e02b1280692f202e04d9ad45ca57de975787ffd63d1"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v20.1.8+0/LLVMOpenMP.v20.1.8.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "850716bd8023a7d6d3e52d86a204ef6378664a60"
libc = "musl"
os = "linux"

    [[LLVMOpenMP.download]]
    sha256 = "624ce87e1daa45527ec2bdc94d1f30f3c72b01cdbf11bf8e36de3148d4bc5340"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v20.1.8+0/LLVMOpenMP.v20.1.8.x86_64-linux-musl-cxx11.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
git-tree-sha1 = "7962da00b77f06187edf49b028bce962cde94a77"
os = "freebsd"

    [[LLVMOpenMP.download]]
    sha256 = "dc81b8569a50f3b7d9dca814910e621def68f035b39d3723a2247bc22b57f837"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v20.1.8+0/LLVMOpenMP.v20.1.8.x86_64-unknown-freebsd.tar.gz"
[[LLVMOpenMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "044a79c763a5d2157b0d5b3b5dd2c74389a4bc1a"
os = "windows"

    [[LLVMOpenMP.download]]
    sha256 = "0f60b0e8073aea93192330f338514454d698e3c0b9aee5f11e622d4a6e8790f6"
    url = "https://github.com/JuliaBinaryWrappers/LLVMOpenMP_jll.jl/releases/download/LLVMOpenMP-v20.1.8+0/LLVMOpenMP.v20.1.8.x86_64-w64-mingw32-cxx11.tar.gz"
